export default {
  name: 'globePin', title: 'Globe Pin', type: 'document',
  fields: [
    { name: 'title', type: 'string', validation: (R: any) => R.required() },
    { name: 'category', type: 'string', options: { list: [
      { title: 'Film Location', value: 'film' }, { title: 'Journal Entry', value: 'journal' },
      { title: 'Gear in the Wild', value: 'gear' }, { title: 'Humanitarian', value: 'humanitarian' },
      { title: 'Travel Story', value: 'story' },
    ]}, validation: (R: any) => R.required() },
    { name: 'latitude', type: 'number', validation: (R: any) => R.required().min(-90).max(90) },
    { name: 'longitude', type: 'number', validation: (R: any) => R.required().min(-180).max(180) },
    { name: 'locationName', type: 'string' },
    { name: 'country', type: 'string' },
    { name: 'date', type: 'date' },
    { name: 'authorName', type: 'string' },
    { name: 'excerpt', type: 'text', rows: 3, validation: (R: any) => R.max(280) },
    { name: 'coverImage', type: 'image', options: { hotspot: true } },
    { name: 'videoUrl', type: 'url' },
    { name: 'linkedFilm', type: 'reference', to: [{ type: 'film' }] },
    { name: 'linkedJournal', type: 'reference', to: [{ type: 'journalEntry' }] },
    { name: 'connectedTo', type: 'reference', to: [{ type: 'globePin' }], description: 'Draw arc to this pin' },
    { name: 'productHandle', type: 'string' },
    { name: 'projectUrl', type: 'url' },
    { name: 'gearUsed', type: 'array', of: [{ type: 'string' }] },
    { name: 'submitterEmail', type: 'string', hidden: true },
    { name: 'consentGiven', type: 'boolean', initialValue: false },
    { name: 'approvalStatus', type: 'string', options: { list: ['approved', 'pending', 'rejected'] }, initialValue: 'approved' },
    { name: 'isCommunitySubmission', type: 'boolean', initialValue: false },
    { name: 'createdAt', type: 'datetime', initialValue: () => new Date().toISOString() },
  ],
  preview: { select: { title: 'title', subtitle: 'locationName', media: 'coverImage' } },
};
